<script setup lang="ts">
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDownToLine,
  ArrowLeft,
  ArrowUpRight,
  ArrowUpFromLine,
  Bell,
  Box,
  Check,
  CheckCheck,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronsLeft,
  ClipboardCheck,
  Clock,
  Copy,
  CornerUpLeft,
  Download,
  Ellipsis,
  Eye,
  EyeOff,
  File,
  FilePlus,
  FileSpreadsheet,
  FileText,
  FileUp,
  Folder,
  FolderLock,
  FolderTree,
  GitBranch,
  HardDrive,
  History,
  Info,
  Layers,
  LayoutDashboard,
  Loader2,
  LogIn,
  LogOut,
  Maximize,
  Maximize2,
  Minus,
  Moon,
  Pencil,
  Plus,
  Power,
  Printer,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Ruler,
  Save,
  Search,
  SearchX,
  ScanLine,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ScrollText,
  Sparkles,
  Square,
  Stamp,
  Sun,
  Trash2,
  Undo2,
  Upload,
  UserCheck,
  UserPlus,
  Users,
  Workflow,
  X,
  Zap,
  ZoomIn,
  ZoomOut,
} from 'lucide-vue-next'

const props = defineProps<{
  name: string
  size?: number
  strokeWidth?: number
}>()

const icons: Record<string, typeof Search> = {
  activity: Activity,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'arrow-down-to-line': ArrowDownToLine,
  'arrow-left': ArrowLeft,
  'arrow-up-from-line': ArrowUpFromLine,
  'arrow-up-right': ArrowUpRight,
  bell: Bell,
  box: Box,
  check: Check,
  'check-check': CheckCheck,
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevrons-left': ChevronsLeft,
  info: Info,
  clipboard: ClipboardCheck,
  'clipboard-check': ClipboardCheck,
  clock: Clock,
  copy: Copy,
  'corner-up-left': CornerUpLeft,
  download: Download,
  ellipsis: Ellipsis,
  eye: Eye,
  'eye-off': EyeOff,
  file: File,
  'file-plus': FilePlus,
  'file-spreadsheet': FileSpreadsheet,
  'file-text': FileText,
  'file-up': FileUp,
  folder: Folder,
  'folder-lock': FolderLock,
  'folder-tree': FolderTree,
  'git-branch': GitBranch,
  'hard-drive': HardDrive,
  history: History,
  layers: Layers,
  'layout-dashboard': LayoutDashboard,
  loader: Loader2,
  'log-in': LogIn,
  'log-out': LogOut,
  maximize: Maximize,
  'maximize-2': Maximize2,
  minus: Minus,
  moon: Moon,
  pencil: Pencil,
  plus: Plus,
  power: Power,
  printer: Printer,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  ruler: Ruler,
  save: Save,
  search: Search,
  'search-x': SearchX,
  'scan-line': ScanLine,
  server: Server,
  settings: Settings,
  'share-2': Share2,
  shield: Shield,
  'shield-check': ShieldCheck,
  'scroll-text': ScrollText,
  sparkles: Sparkles,
  square: Square,
  stamp: Stamp,
  sun: Sun,
  'trash-2': Trash2,
  'undo-2': Undo2,
  upload: Upload,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  users: Users,
  workflow: Workflow,
  x: X,
  zap: Zap,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
}
</script>

<template>
  <component
    :is="icons[props.name] ?? Search"
    :size="props.size ?? 16"
    :stroke-width="props.strokeWidth ?? 2"
    aria-hidden="true"
  />
</template>
